device: cuda:0
image_model: facebook/deit-base-distilled-patch16-224
text_model: bert-base-multilingual-uncased
intermediate_dim: 512
model_folder: bert_multi_deit_ukr
checkpoint: checkpoint-3100
dataset_root_dir: dataset
dataset_dir: ukr
answer_space_filename: answer_space.txt
